############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "The Team"
url = "team/"
weight = 3

[[main]]
name = "Gallery"
url = "/gallery"
weight = 4

[[main]]
name = "Rules"
url = "/rules"
weight = 5


# footer menu
[[footer]]
name = "About ConQ"
url = "about/"
weight = 1

[[footer]]
name = "Register"
url = "register/"
weight = 2


