############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "The Team"
url = "team/"
weight = 3


[[main]]
name = "Highlights"
url = "highlights/"



# footer menu
[[footer]]
name = "About ConQ"
url = "about/"
weight = 1

[[footer]]
name = "Register"
url = "register/"
weight = 2

[[footer]]
name = "FAQ"
url = "faqs/"
weight = 3
